catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
packages:
  - nextjs-app
  - rari-app
  - shared
catalogs:
  build:
    rolldown-vite: ^7.3.1
  default:
    '@types/node': ^25.3.0
    '@typescript/native-preview': ^7.0.0-dev.20260223.1
    oxlint: ^1.50.0
    rari: ^0.10.3
    typescript: ^5.9.3
  eslint:
    '@antfu/eslint-config': ^7.4.3
    '@eslint-react/eslint-plugin': ^2.13.0
    eslint: ^10.0.1
    eslint-plugin-oxlint: ^1.50.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.5.2
  md:
    '@types/markdown-it': ^14.1.2
    markdown-it: ^14.1.1
  nextjs:
    next: ^16.1.6
  react:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwind:
    '@tailwindcss/postcss': ^4.2.1
    '@tailwindcss/vite': ^4.2.1
    tailwindcss: ^4.2.1
