catalogMode: prefer
minimumReleaseAgeExclude:
  - '@rari/use-cache-darwin-arm64@0.15.3'
  - '@rari/use-cache-darwin-x64@0.15.3'
  - '@rari/use-cache-linux-arm64@0.15.3'
  - '@rari/use-cache-linux-x64@0.15.3'
  - '@rari/use-cache-win32-arm64@0.15.3'
  - '@rari/use-cache-win32-x64@0.15.3'
  - '@rari/use-cache@0.15.3'
  - rari-darwin-arm64@0.15.3
  - rari-darwin-x64@0.15.3
  - rari-linux-arm64@0.15.3
  - rari-linux-x64@0.15.3
  - rari-win32-arm64@0.15.3
  - rari-win32-x64@0.15.3
  - rari@0.15.3
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
packages:
  - apps/nextjs
  - apps/rari
  - shared
catalogs:
  build:
    vite: ^8.1.4
  default:
    oxlint: ^1.73.0
    rari: ^0.15.3
  eslint:
    '@antfu/eslint-config': ^9.1.0
    '@eslint-react/eslint-plugin': ^5.14.8
    eslint: ^10.7.0
    eslint-plugin-oxlint: ^1.73.0
    eslint-plugin-react-refresh: ^0.5.3
  md:
    '@types/markdown-it': ^14.1.2
    markdown-it: ^14.3.0
  nextjs:
    next: ^16.2.10
  react:
    '@types/react': ^19.2.17
    '@types/react-dom': ^19.2.3
    react: ^19.2.7
    react-dom: ^19.2.7
  tailwind:
    '@tailwindcss/postcss': ^4.3.2
    '@tailwindcss/vite': ^4.3.2
    tailwindcss: ^4.3.2
  typescript:
    '@types/node': ^26.1.1
    # https://devblogs.microsoft.com/typescript/announcing-typescript-7-0/#running-side-by-side-with-typescript-6.0
    typescript: npm:@typescript/typescript6@^6.0.2
    typescript-7: npm:typescript@^7.0.2
allowBuilds:
  sharp: true
