catalogMode: prefer
minimumReleaseAgeExclude:
  - '@rari/use-cache-darwin-arm64@0.15.8'
  - '@rari/use-cache-darwin-x64@0.15.8'
  - '@rari/use-cache-linux-arm64@0.15.8'
  - '@rari/use-cache-linux-x64@0.15.8'
  - '@rari/use-cache-win32-arm64@0.15.8'
  - '@rari/use-cache-win32-x64@0.15.8'
  - '@rari/use-cache@0.15.8'
  - rari-darwin-arm64@0.15.8
  - rari-darwin-x64@0.15.8
  - rari-linux-arm64@0.15.8
  - rari-linux-x64@0.15.8
  - rari-win32-arm64@0.15.8
  - rari-win32-x64@0.15.8
  - rari@0.15.8
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
packages:
  - apps/nextjs
  - apps/rari
  - shared
catalogs:
  build:
    vite: ^8.2.0
  default:
    oxlint: ^1.77.0
    rari: ^0.15.8
  eslint:
    '@antfu/eslint-config': ^9.2.0
    '@eslint-react/eslint-plugin': ^5.18.2
    eslint: ^10.8.0
    eslint-plugin-oxlint: ^1.77.0
    eslint-plugin-react-refresh: ^0.5.3
  md:
    '@types/markdown-it': ^14.1.2
    markdown-it: ^15.0.0
  nextjs:
    next: ^16.3.0
  react:
    '@types/react': ^19.2.18
    '@types/react-dom': ^19.2.4
    react: ^19.2.8
    react-dom: ^19.2.8
  tailwind:
    '@tailwindcss/postcss': ^4.3.3
    '@tailwindcss/vite': ^4.3.3
    tailwindcss: ^4.3.3
  typescript:
    '@types/node': ^26.1.2
    # https://devblogs.microsoft.com/typescript/announcing-typescript-7-0/#running-side-by-side-with-typescript-6.0
    typescript: npm:@typescript/typescript6@^6.0.2
    typescript-7: npm:typescript@^7.0.2
allowBuilds:
  sharp: true
